name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
      - name: verify java installation
        run: |
          java -version
          javac -version
      - name: install maven
        run: |
          sudo apt install maven -y
      - name: verify maven installation
        run: |
          mvn -v
      - name: clone from github repository
        run: |
          git clone https://github.com/mahendrasaidoddi/springboot-postgresql-docker.git
      - name: git checkout to master branches:
        run: |
          cd springboot-postgresql-docker
          git checkout master
      - name: mvn clean install
        run: |
          mvn clean install
      - name: run the application
        run: |
          cd target
          nohup java -jar springboot-postgresql-docker-0.0.1-SNAPSHOT.jar &
      - name: verify the application is running or not
        run: |
          curl -I localhost:8080 || echo "Application is not responding on localhost:8080"  
      - name: check if the application is running using if else condition
        run: |
          if curl -I localhost:8080; then
              echo "Application is running"
          else
              echo "Application is not running"
          fi
