name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nginx
        run: |
          sudo apt update
          sudo apt install nginx -y
      - name: verify nginx installation
        run: |
          nginx -v
          systemctl status nginx || echo "Nginx installed, but service not running" 
          curl -I localhost || echo "Nginx is not responding on localhost"
          sudo systemctl start nginx
          sudo systemctl enable nginx
          systemctl status nginx
      - name: clone from github repository
        run: |
          git clone https://github.com/Sardar74/main.git
          cd main
      - name: copy index.html to nginx default directory
        run: |
          sudo cp main/saas-website-template /var/www/html/
      - name: add the content in default nginx configuration file
        run: |
          echo 'server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html/saas-website-template/;
              index index.html index.htm index.nginx-debian.html;
              server_name _;
              location / {
                  try_files $uri $uri/ =404;
              }
          }' | sudo tee /etc/nginx/sites-available/default
      - name: restart nginx service
        run: |
          sudo systemctl restart nginx
      - name: add if else condition to check nginx service status
        run: |
          if systemctl is-active --quiet nginx; then
              echo "Nginx is running"
          else
              echo "Nginx is not running"
          fi
