name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
      - name: verify java installation
        run: |
          java -version
          javac -version
      - name: Sonar install latest version
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.2.0.53491.zip
          sudo apt install unzip -y
          unzip sonarqube-10.2.0.53491.zip
          sudo mv sonarqube-10.2.0.53491 /opt/sonarqube
          sudo chown -R $USER:$USER /opt/sonarqube
      - name: Start SonarQube server
        run: |
          /opt/sonarqube/bin/linux-x86-64/sonar.sh start
      - name: Verify SonarQube server is running
        run: |  
          if curl -I http://localhost:9000; then
              echo "SonarQube server is running"
          else
              echo "SonarQube server is not running"
          fi
