name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib

      - name: Verify PostgreSQL installation
        run: |
          psql --version
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo systemctl status postgresql --no-pager

      - name: Set postgres user password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'YourNewPassword';"

      - name: Configure PostgreSQL to listen on all interfaces
        run: |
          PG_VERSION=$(psql -V | awk '{print $3}' | cut -d. -f1)
          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/$PG_VERSION/main/postgresql.conf
          echo "host    all    all    0.0.0.0/0    md5" | sudo tee -a /etc/postgresql/$PG_VERSION/main/pg_hba.conf
          sudo systemctl restart postgresql

      - name: Verify PostgreSQL listening
        run: |
          if sudo ss -plunt | grep postgres; then
            echo "PostgreSQL is listening on all interfaces"
          else
            echo "PostgreSQL is NOT listening on all interfaces"
          fi

      - name: Create a new database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE mydatabase;"

      - name: Insert data into database
        run: |
          sudo -u postgres psql -d mydatabase -c "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(100));"
          sudo -u postgres psql -d mydatabase -c "INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');"

      - name: Verify data
        run: |
          sudo -u postgres psql -d mydatabase -c "SELECT * FROM users;"
