name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
      - name: verify java installation
        run: |
          java -version
          javac -version
      - name: Sonar install latest version
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.8.0.112029.zip          sudo apt install unzip -y
          unzip sonarqube-25.8.0.112029.zip
          sudo mv sonarqube-25.8.0.112029 /opt/sonarqube
      - name: create a new user name sonarqube
        run: |
          sudo adduser --system --no-create-home --group --disabled-login sonarqube
      - name: create a new group name sonarGroup
        run: |
          sudo groupadd sonarGroup
      - name: add the user sonarqube to sonarGroup
        run: |
          sudo usermod -a -G sonarGroup sonarqube
      - name: change the ownership of the sonarqube directory
        run: |
          sudo chown -R sonarqube:sonarGroup /opt/sonarqube         
          sudo chmod -R 750 /opt/sonarqube
      - name: start sonarqube server
        run: |
          sudo -u sonarqube /opt/sonarqube/bin/linux-x86-64/sonar.sh start
      - name: verify sonarqube server is running or not
        run: |
          curl -I localhost:9000 || echo "Sonarqube is not responding on localhost:9000"  
      - name: check if the sonarqube server is running using if else condition
        run: |
          if curl -I localhost:9000; then
              echo "Sonarqube server is running"
          else
              echo "Sonarqube server is not running"
          fi
      - name: check sonarcube status
        run: |
          sudo -u sonarqube /opt/sonarqube/bin/linux-x86-64/sonar.sh status
      
